### ISSUE TITLE
Login ne radi

### ISSUE THREAD

**Issue by llemes** [SoftverInzenjeringETFSA/2018_ReaderM#1]
**Komponenta:** LoginForm
**Commit ID:** 1d09e2edf6187399efe486f10660798af392543e
**Opis greške:** Login ne radi
**Koraci za reproduciranje:**

 1. Pokrenuti aplikaciju ReaderM
 2. U polje email ukucati ‘MaidBajramovic’
 3. U polje password ukucati ‘123456’
 4. Kliknuti na dugme ‘Login’

**Dobijeni rezultat:** Ništa se ne desi.
**Očekivani rezultat:** Redirect na sadržaj aplikacije nakon uspješnog logina.
**Dodatne informacije:** Login je testiran i na web aplikaciji Reader, gdje uspješno prolazi sa ovim podacima. IP adresa na kojoj se nalazi backend je također promijenjena, te se u konzolu ispisuje da je server vratio status 200 (OK).

**Comment by muratovicnedim** [comment]
Login is now working as requested.
