### ISSUE TITLE
Neadekvatno uputstvo za pokretanje projekta

### ISSUE THREAD

**Issue by llemes** [SoftverInzenjeringETFSA/2018_ReaderM#3]
**Komponenta:** Uputstvo za pokretanje projekta
**Commit ID:** 1d09e2edf6187399efe486f10660798af392543e
**Opis greške:** Uputstvo za pokretanje projekta je nepotpuno.
**Koraci za reproduciranje:**

 1. Ulazak na [repozitorij projekta](https://github.com/SoftverInzenjeringETFSA/2018_ReaderM).
 2. Pregled *README.md* file-a.

**Dobiveni rezultat:** Pokretanje frontenda aplikacije
**Očekivani rezultat:** Pokretanje i frontenda i backenda aplikacije
**Dodatne informacije:** 

Da bi cijeli projekat uspješno funkcionisao, neophodno je pokrenuti i njegov frontend, i njegov backend. U uputstvu za pokretanje projekta opisano je samo pokretanje frontenda projekta, no za pokretanje backenda potrebno je klonirati [drugi repozitorij](https://github.com/SoftverInzenjeringETFSA/2018_Reader) te pratiti upustva za njegovo pokretanje zbog rada sa backendom. U uputstvu za pokretanje projekta ovaj dio ni na koji način nije tretiran.

Pored ovoga, nije naglašeno da je potrebno promijeniti IP adresu na kojoj je backend pokrenut, što je zahtijevalo kopanje po kodu nakon nekoliko bezuspješnih network requestova.

Na kraju, aplikacija koja je deployana nije dostupna za pregled nikome osim osobi koja je uradila deploy, tako da se aplikacija ne može pokrenuti ni na taj način. Screenshot se nalazi ispod.

![img_4574](https://user-images.githubusercontent.com/10695431/41300329-b82fcc88-6e65-11e8-8313-8318761009fd.PNG)

**Comment by muratovicnedim** [comment]
Deployed app is now public and can be accessed by anyone.
Backend is also deployed and made available through that expo app.
